Wrong number of arguments: call(foo,[10])